- name: create Secrets on k8s for hcloud drivers
  hosts: master1
  tasks:
    - debug:
        msg: "tf_hcloud_token is - {{lookup('file', '../tf_hcloud_token') }}"
    - debug:
        msg: "tf_hcloud_network_id is - {{lookup('file', '../tf_hcloud_network_id') }}"
    - name: Create Secrets
      shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: hcloud
          namespace: kube-system
        stringData:
          token: "{{lookup('file', '../tf_hcloud_token') }}"
          network: "{{lookup('file', '../tf_hcloud_network_id') }}"
        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: hcloud-csi
          namespace: kube-system
        stringData:
          token: "{{lookup('file', '../tf_hcloud_token') }}"
        EOF
